#define YGFX_ALICE_BLUE         0
#define YGFX_ALIZARIN_CRIMSON   1
#define YGFX_ANTIQUE_WHITE      2
#define YGFX_AQUAMARINE         3
#define YGFX_AQUAMARINEMEDIUM   4
#define YGFX_AUREOLINE_YELLOW   5
#define YGFX_AZURE              6
#define YGFX_BANANA             7
#define YGFX_BEIGE              8
#define YGFX_BISQUE             9
#define YGFX_BLACK              10
#define YGFX_BLANCHED_ALMOND    11
#define YGFX_BLUE               12
#define YGFX_BLUE_LIGHT         13
#define YGFX_BLUE_MEDIUM        14
#define YGFX_BLUE_VIOLET        15
#define YGFX_BRICK              16
#define YGFX_BROWN              17
#define YGFX_BROWN_MADDER       18
#define YGFX_BROWN_OCHRE        19
#define YGFX_BURLYWOOD          20
#define YGFX_BURNT_SIENNA       21
#define YGFX_BURNT_UMBER        22
#define YGFX_CADET              23
#define YGFX_CADMIUM_LEMON      24
#define YGFX_CADMIUM_ORANGE     25
#define YGFX_CADMIUM_RED_DEEP   26
#define YGFX_CADMIUM_RED_LIGHT  27
#define YGFX_CADMIUM_YELLOW     28
#define YGFX_CARROT             29
#define YGFX_CERULEAN           30
#define YGFX_CHARTREUSE         31
#define YGFX_CHOCOLATE          32
#define YGFX_CHROMEOXIDEGREEN   33
#define YGFX_CINNABAR_GREEN     34
#define YGFX_COBALT             35
#define YGFX_COBALT_GREEN       36
#define YGFX_COBALT_VIOLETDEEP  37
#define YGFX_COLD_GREY          38
#define YGFX_CORAL              39
#define YGFX_CORAL_LIGHT        40
#define YGFX_CORNFLOWER         41
#define YGFX_CORNSILK           42
#define YGFX_CYAN               43
#define YGFX_CYAN_WHITE         44
#define YGFX_DARK_ORANGE        45
#define YGFX_DEEP_OCHRE         46
#define YGFX_DEEP_PINK          47
#define YGFX_DIM_GREY           48
#define YGFX_DODGER_BLUE        49
#define YGFX_EGGSHELL           50
#define YGFX_EMERALD_GREEN      51
#define YGFX_ENGLISH_RED        52
#define YGFX_FIREBRICK          53
#define YGFX_FLESH              54
#define YGFX_FLESH_OCHRE        55
#define YGFX_FLORAL_WHITE       56
#define YGFX_FOREST_GREEN       57
#define YGFX_GAINSBORO          58
#define YGFX_GERANIUM_LAKE      59
#define YGFX_GHOST_WHITE        60
#define YGFX_GOLD               61
#define YGFX_GOLDENROD          62
#define YGFX_GOLDENROD_DARK     63
#define YGFX_GOLDENROD_LIGHT    64
#define YGFX_GOLDENROD_PALE     65
#define YGFX_GOLD_OCHRE         66
#define YGFX_GREEN              67
#define YGFX_GREENISH_UMBER     68
#define YGFX_GREEN_DARK         69
#define YGFX_GREEN_PALE         70
#define YGFX_GREEN_YELLOW       71
#define YGFX_GREY               72
#define YGFX_HONEYDEW           73
#define YGFX_HOT_PINK           74
#define YGFX_INDIAN_RED         75
#define YGFX_INDIGO             76
#define YGFX_IVORY              77
#define YGFX_IVORY_BLACK        78
#define YGFX_KHAKI              79
#define YGFX_KHAKI_DARK         80
#define YGFX_LAMP_BLACK         81
#define YGFX_LAVENDER           82
#define YGFX_LAVENDER_BLUSH     83
#define YGFX_LAWN_GREEN         84
#define YGFX_LEMON_CHIFFON      85
#define YGFX_LIGHT_BEIGE        86
#define YGFX_LIGHT_GOLDENROD    87
#define YGFX_LIGHT_GREY         88
#define YGFX_LIGHT_SALMON       89
#define YGFX_LIME_GREEN         90
#define YGFX_LINEN              91
#define YGFX_MADDER_LAKE_DEEP   92
#define YGFX_MAGENTA            93
#define YGFX_MANGANESE_BLUE     94
#define YGFX_MAROON             95
#define YGFX_MARS_ORANGE        96
#define YGFX_MARS_YELLOW        97
#define YGFX_MELON              98
#define YGFX_MIDNIGHT_BLUE      99
#define YGFX_MINT               100
#define YGFX_MINT_CREAM         101
#define YGFX_MISTY_ROSE         102
#define YGFX_MOCCASIN           103
#define YGFX_NAPLESYELLOWDEEP   104
#define YGFX_NAVAJO_WHITE       105
#define YGFX_NAVY               106
#define YGFX_OLD_LACE           107
#define YGFX_OLIVE              108
#define YGFX_OLIVE_DRAB         109
#define YGFX_OLIVE_GREEN_DARK   110
#define YGFX_ORANGE             111
#define YGFX_ORANGE_RED         112
#define YGFX_ORCHID             113
#define YGFX_ORCHID_DARK        114
#define YGFX_ORCHID_MEDIUM      115
#define YGFX_PAPAYA_WHIP        116
#define YGFX_PEACH_PUFF         117
#define YGFX_PEACOCK            118
#define YGFX_PERMANENT_GREEN    119
#define YGFX_PERMANENT_VIOLET   120
#define YGFX_PERU               121
#define YGFX_PINK               122
#define YGFX_PINK_LIGHT         123
#define YGFX_PLUM               124
#define YGFX_POWDER_BLUE        125
#define YGFX_PURPLE             126
#define YGFX_PURPLE_MEDIUM      127
#define YGFX_RASPBERRY          128
#define YGFX_RAW_SIENNA         129
#define YGFX_RAW_UMBER          130
#define YGFX_RED                131
#define YGFX_ROSE_MADDER        132
#define YGFX_ROSY_BROWN         133
#define YGFX_ROYAL_BLUE         134
#define YGFX_SADDLE_BROWN       135
#define YGFX_SALMON             136
#define YGFX_SANDY_BROWN        137
#define YGFX_SAP_GREEN          138
#define YGFX_SEASHELL           139
#define YGFX_SEA_GREEN          140
#define YGFX_SEA_GREEN_DARK     141
#define YGFX_SEA_GREEN_LIGHT    142
#define YGFX_SEA_GREEN_MEDIUM   143
#define YGFX_SEPIA              144
#define YGFX_SIENNA             145
#define YGFX_SKY_BLUE           146
#define YGFX_SKY_BLUE_DEEP      147
#define YGFX_SKY_BLUE_LIGHT     148
#define YGFX_SLATE_BLUE         149
#define YGFX_SLATE_BLUE_DARK    150
#define YGFX_SLATE_BLUE_LIGHT   151
#define YGFX_SLATE_BLUE_MEDIUM  152
#define YGFX_SLATE_GREY         153
#define YGFX_SLATE_GREY_DARK    154
#define YGFX_SLATE_GREY_LIGHT   155
#define YGFX_SNOW               156
#define YGFX_SPRING_GREEN       157
#define YGFX_SPRING_GREENMEDIUM 158
#define YGFX_STEEL_BLUE         159
#define YGFX_STEEL_BLUE_LIGHT   160
#define YGFX_TAN                161
#define YGFX_TERRE_VERTE        162
#define YGFX_THISTLE            163
#define YGFX_TITANIUM_WHITE     164
#define YGFX_TOMATO             165
#define YGFX_TURQUOISE          166
#define YGFX_TURQUOISE_BLUE     167
#define YGFX_TURQUOISE_DARK     168
#define YGFX_TURQUOISE_MEDIUM   169
#define YGFX_TURQUOISE_PALE     170
#define YGFX_ULTRAMARINE        171
#define YGFX_ULTRAMARINE_VIOLET 172
#define YGFX_VAN_DYKE_BROWN     173
#define YGFX_VENETIAN_RED       174
#define YGFX_VIOLET             175
#define YGFX_VIOLET_DARK        176
#define YGFX_VIOLET_RED         177
#define YGFX_VIOLET_REDMEDIUM   178
#define YGFX_VIOLET_RED_PALE    179
#define YGFX_VIRIDIAN_LIGHT     180
#define YGFX_WARM_GREY          181
#define YGFX_WHEAT              182
#define YGFX_WHITE              183
#define YGFX_WHITE_SMOKE        184
#define YGFX_YELLOW             185
#define YGFX_YELLOW_GREEN       186
#define YGFX_YELLOW_LIGHT       187
#define YGFX_YELLOW_OCHRE       188
#define YGFX_ZINC_WHITE         189
