#include "yocto/utest/driver.hpp"

YOCTO_UNIT_TEST_INIT(16)
{
	YOCTO_UNIT_TEST_DECL(inf);
	YOCTO_UNIT_TEST_DECL(def);
	YOCTO_UNIT_TEST_DECL(iz);
	YOCTO_UNIT_TEST_DECL(oz);
    YOCTO_UNIT_TEST_DECL(codec32);
}
YOCTO_UNIT_TEST_EXEC()
