all:

clean:
	rm -f *.toc *.aux *.log *.synctex.gz newton.ps newton.pdf psd.ps psd.pdf splines.ps splines.pdf shapes.pdf shapes.ps lsf.pdf lsf.ps least-squares.ps least-squares.pdf pade.ps pade.pdf gnllsf.ps gnllsf.pdf drvs.pdf drvs.ps cubic-spline.ps cubic-spline.pdf cwt.pdf cwt.ps smooth.pdf smooth.ps kde.pdf kde.pdf



