#include "yocto/utest/driver.hpp"


YOCTO_UNIT_TEST_INIT(16)
{
	YOCTO_UNIT_TEST_DECL(layouts);
	
	YOCTO_UNIT_TEST_DECL(a1D);
	YOCTO_UNIT_TEST_DECL(a2D);
	YOCTO_UNIT_TEST_DECL(a3D);
	
	YOCTO_UNIT_TEST_DECL(w1D);
	YOCTO_UNIT_TEST_DECL(w2D);
	YOCTO_UNIT_TEST_DECL(w3D);
	
	YOCTO_UNIT_TEST_DECL(s1D);
	YOCTO_UNIT_TEST_DECL(s2D);
	
	YOCTO_UNIT_TEST_DECL(ppm);
	
	YOCTO_UNIT_TEST_DECL(bresenham);
}
YOCTO_UNIT_TEST_EXEC()
